### ISSUE TITLE
Add Onion Name for K-Tipp

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#110]
Please create the short onion name `ktipp.securedrop.tor.onion` for K-Tipp.

Directory entry: https://securedrop.org/directory/k-tipp/
Long onion address: tukldpfzdizsrfyvdljnipmvix2dcb5hmfoemcidkw7bq56wxblk6did.onion

Thank you!

**Comment by zenmonkeykstop** [comment]
This was closed in #111
