### ISSUE TITLE
Add Onion Name for Taz

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#115]
Please create the short onion name `taz.securedrop.tor.onion` for Taz.

Directory entry: https://securedrop.org/directory/taz/
Long onion address: tazleakssvtc2lqrhkpvbzo6qwolcldzkzoexo7wombufd6a573bhlid.onion

Thank you!

**Comment by zenmonkeykstop** [comment]
onion name generation failing as there are a bunch of instances missing from the directory:

-lessig.law,lessig.securedrop.tor.onion - **DECOMMISSIONED**
-www.reuters.com,reuters.securedrop.tor.onion **DECOMMISSIONED**
-propublica.org,propublica.securedrop.tor.onion **??**
-nex.sx,nex.securedrop.tor.onion **??**
-aftenbladet.no,aftenbladet.securedrop.tor.onion **??**

Can you confirm whether the ones marked **??**  should be removed?

**Comment by nathandyer** [comment]
@zenmonkeykstop There are some specifics/nuances I don't want to share publicly, so I'll share them with you privately using one of our encrypted platforms. Generally speaking, though, only `nex.sx,nex.securedrop.tor.onion` from your ?? list above can be removed for now.

**Comment by nathandyer** [comment]
Fixed by #116
