### ISSUE TITLE
Add Short Onion Name for The Economist

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#189]
Please create the short onion name `theeconomist.securedrop.tor.onion` for The Economist

Directory entry: https://securedrop.org/directory/the-economist/
Long onion address: `mxmddqsh4jnr4gjan37ayin3fu5ecnejxge4wjhj4i45qq5djbxdjtad.onion`

Thank you!

**Comment by legoktm** [comment]
I was going to say something about `the` but it seems we already have a few outlets with the article in front (The Guardian, TGAM).
