### ISSUE TITLE
Duplicate ABC ruleset is generated

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-https-everywhere-ruleset#20]
First reported in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/19#issuecomment-737487314 Rerunning the `sddir.py` script generates an uncommitted ruleset for ABC:

```
$ git show
commit 276c1da5f83bef16661d4367772a7b50f611701a (HEAD -> main, rocodes/main, origin/main)
Merge: 72325dd 4d48d4a
Author: mickael e <emkll@users.noreply.github.com>
Date:   Wed Nov 4 17:20:51 2020 -0500

    Merge pull request #18 from freedomofpress/13-add-harvard-iqss
    
    Add Harvard IQSS to ruleset

[user@sd-dev:~/securedrop-https-everywhere-ruleset] [httpse] main+ 1h50m5s ± 
 $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
[user@sd-dev:~/securedrop-https-everywhere-ruleset] [httpse] main+ 1h50m8s ± 
 $ python3 sddir.py 
✔️ Custom rulesets written to directory: ./rulesets
[user@sd-dev:~/securedrop-https-everywhere-ruleset] [httpse] main+* 1h50m12s ± 
 $ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	rulesets/abc-securedrop-ruleset.xml

nothing added to commit but untracked files present (use "git add" to track)
```

The difference between the untracked file and the pre-existing ABC ruleset is minor:

```
$ diffoscope rulesets/abc-*
--- rulesets/abc-au-securedrop-ruleset.xml
+++ rulesets/abc-securedrop-ruleset.xml
│   --- rulesets/abc-au-securedrop-ruleset.xml
├── +++ rulesets/abc-securedrop-ruleset.xml
│ @@ -1,5 +1,5 @@
│  <?xml version="1.0" encoding="utf-8"?>
│ -<ruleset name="ABC AU">
│ +<ruleset name="ABC">
│    <target host="abc.au.securedrop.tor.onion"/>
│    <rule from="^http[s]?://abc.au.securedrop.tor.onion" to="http://dqa4zahticcobfq5rmmmbewbdtyiznbl75hu23k4i37y7yfoosrh7mqd.onion"/>
│  </ruleset>
```

but nonetheless should be resolved.

**Comment by conorsch** [comment]
@emkll Could I trouble you to have a look at this? To my eye, we just need a copy edit in the ruleset generation file, but would appreciate a sanity check on that so I don't break anything. This isn't blocking new additions, but would still like to clean it up to avoid mistakes.

**Comment by emkll** [comment]
It appears like the rule was improperly generated/added to the ruleset when it was introduced: The name of the file and the name of the site should correspond to the slug on the directory, and as such the existing rule was incorrect. I've appended a commit to https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/27/ to resolve this issue, and should not pose a problem in future ruleset upgrades.
