### ISSUE TITLE
Script the signing procedures as much as possible

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-https-everywhere-ruleset#22]
We have a few sources of documentation describing the workflow to generate new rulesets and the corresponding signature. Many of the steps are manual commands that can easily be scripted. Since we use an airgapped signing process (as described in https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/ruleset-update-channels.md#signing), we can't script everything, but we sure can put the process on rails. 

While working on https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/19 I cobbled together a crude script that I'll submit as a draft for review.

**Comment by emkll** [comment]
Let's consider this closed via #23 . We can open more specific issues for signing/release automation in the future, as necessary.
