### ISSUE TITLE
Add Stefania Maurizi

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#24]
Requested onion name `maurizi.securedrop.tor.onion`
Landing page: https://stefaniamaurizi.it/en-contactme.html
Directory: https://securedrop.org/directory/stefania-maurizi/ (v3 address update pending)

**Comment by conorsch** [comment]
I'll take this one. Waiting for merge of #19, then will add.

**Comment by conorsch** [comment]
Whoops, let this one slip. We just got another request, in #26, so I'll tackle together.

**Comment by conorsch** [comment]
> Directory: https://securedrop.org/directory/stefania-maurizi/ (v3 address update pending)

Update: the v3 address is live in the directory, so I'll use the v3 in the ruleset update: `jxsb4ovmavjy3r64bak4ha63xwggf3nzf3vikvs23r2avm5rhzmaqtqd.onion`
