### ISSUE TITLE
Add Forbes

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#26]
Requested onion name: forbes.securedrop.tor.onion
v3 address: see https://www.forbes.com/fdc/securedrop.html

**Comment by conorsch** [comment]
> v3 address: see https://www.forbes.com/fdc/securedrop.html

The landing page is still showing a v2 address (`t5pv5o4t6jyjilp6.onion`). I do see a v3 in the directory, though: https://securedrop.org/directory/forbes/ , and that value (`o6ajg2e6i6rnw5oihquvd4e64toxblnh62aoko4aimgapsowefsnhead.onion`) matches what's in the v2 metadata endpoint, so will proceed with that.
