### ISSUE TITLE
Add onion name for Bart Gellman

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#29]
Bart has requested an onion name for his SecureDrop (via direct comms w/ Kev and myself).

- Onion address: See landing page https://tcfmailvault.info/
- v3 enabled: yes
- Directory entry: https://securedrop.org/directory/barton-gellman/
- Requested onion name: `bartongellman.securedrop.tor.onion`

**Comment by emkll** [comment]
closed via #32
