### ISSUE TITLE
Missing A record www.pressfreedomfoundation.org

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop-https-everywhere-ruleset#36]
https everywhere to .onion fails for www.pressfreedomfoundation.org 

0. https everywhere/Tor browser send me from http://www.pressfreedomfoundation.org to https://www.pressfreedomfoundation.org
1. there's no DNS entry for www.pressfreedomfoundation.org (there is one for pressfreedomfoundation.org)
-> failur

Expected to have the same behavior as when using http://pressfreedomfoundation.org in Tor browser I get sent to  http://fpfjxcrmw437h6z2xl3w4czl55kvkmxpapg37bbopsafdu7q454byxid.onion/  like it should (setting the always use onion when available).

This place is the closest I could get for filing this issue.

**Comment by conorsch** [comment]
Thanks, @KwadroNaut, very clear report. FYI, that's an outdated URL you're sharing. These days we're at https://freedom.press. But you're absolutely right, we should add that "www" subdomain as you suggest, that must have fallen off at some point.

**Comment by conorsch** [comment]
Fixed! Thanks again for reporting, @KwadroNaut . Do let us know if you have any more trouble.
