### ISSUE TITLE
Point to HTTPS onion address for onion services that support it

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#4]
So far all the .onion addresses I've tested with did not use an EV SSL cert; it'd be good to document the behavior for .onion addresses that use one (e.g., is the EV information still shown?).

**Comment by eloquence** [comment]
Currently the behavior is that we hardcode `http://` because the preferred protocol is not exposed through the directory API. HTTP onions with HTTPS enabled redirect there, so the EV cert information is still visible and the connection still ultimately uses HTTPS.

Hardcoding http:// in the first place is not great (albeit relatively harmless given onion service level encryption), but needs to be resolved at the directory level. This is tracked here: https://github.com/freedomofpress/securedrop.org/issues/832

Retitling this issue and marking as blocked for now.

**Comment by legoktm** [comment]
This is no longer blocked as the information is now surfaced in the directory, here's the NYT response for example:
```json
        "latest_scan": {
            "landing_page_url": "https://www.nytimes.com/tips",
            "redirect_target": null,
            "live": true,
            "result_last_seen": "2022-11-29T14:23:00.227312Z",
            "forces_https": true,
            "hsts": true,
            "hsts_max_age": true,
            "hsts_entire_domain": false,
            "hsts_preloaded": false,
            "http_status_200_ok": true,
```

**Comment by zenmonkeykstop** [comment]
I think `forces_https` here refers to the landing page scanner results? This is separate to the protocol for the onion service.

**Comment by legoktm** [comment]
Ugh you're right, I don't actually see where this is exposed in the directory. I'm a bit confused though, https://github.com/freedomofpress/securedrop.org/issues/832 is marked as done back in 2021, so are we missing exposing that property in the API? Or does it still need to be populated in the directory?
