### ISSUE TITLE
Add The Guardian

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#6]
The Guardian has agreed to be included in the next ruleset update. Information about the instance can be found in its directory entry, which should be validated against their landing page:

https://securedrop.org/directory/guardian/

They have requested the onion name `theguardian.securedrop.tor.onion`.

**Comment by redshiftzero** [comment]
@kushaldas - 

For this we could do the following:
1. Add a new organization following: https://github.com/freedomofpress/securedrop-https-everywhere-ruleset#adding-a-new-organization
2. Run the first script in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset#release-process: (`python sddir.py`)
3. Do the signing process with a test key + test the redirect works as expected
4. Create a draft PR with the updates to `rulesets/` which we can then sign with the prod key
