### ISSUE TITLE
Toronto Star .onion address is out of date

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#60]
Toronto Star's .onion address recently changed; see https://www.thestar.com/securedrop.html . We need to update `torontostar.securedrop.tor.onion` to point to the new address.

Note that I've delisted the onion name from https://securedrop.org/directory/toronto-star/ for now, so we'll need to reinstate that once the onion name has been updated.

**Comment by eloquence** [comment]
This was resolved on the primary endpoint via #61 but still needs to be ported to the 2021 endpoint.

**Comment by zenmonkeykstop** [comment]
Will be resolved on 2021 channel by #58.

**Comment by eloquence** [comment]
Done.
