### ISSUE TITLE
Plan for post-HTTPSEverywhere future

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#67]
EFF is planning to retire HTTPSEverywhere after a maintenance period in 2022:
https://www.eff.org/deeplinks/2021/09/https-actually-everywhere

Let's coordinate w/ upstream to ensure we preserve access to onion name functionality in Tor Browser.

**Comment by eloquence** [comment]
@Hainish Sounds like we have plenty of time to sort this out, but curious if y'all have already been in touch with Tor Project folks about the deprecation?

**Comment by zenmonkeykstop** [comment]
We can close this, as https-everywhere functionality has been integrated into TBB.
