### ISSUE TITLE
Add onion name for ProPublica

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#87]
Onion name: propublica.securedrop.tor.onion
Directory entry: https://securedrop.org/directory/propublica/

**Comment by conorsch** [comment]
@creviera assigning this one to you. Steps to complete are:

1. Branch from main in this repo
2. Edit `onboarded.txt` to include the org info (see patch below)
3. Run `make rules` to generate new ruleset
4. Complete signing procedure on airgap

<details>
<summary>
example patch
</summary>

```
diff --git a/onboarded.txt b/onboarded.txt
index c1bb5ec..ee3bcac 100644
--- a/onboarded.txt
+++ b/onboarded.txt
@@ -30,3 +30,4 @@ lessig.law,lessig.securedrop.tor.onion
 news.bloomberglaw.com,bloomberglaw.securedrop.tor.onion
 www.reuters.com,reuters.securedrop.tor.onion
 www.cnn.com,cnn.securedrop.tor.onion
+propublica.org,propublica.securedrop.tor.onion
```

</details>
