### ISSUE TITLE
Onion name for nex

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#89]
Originally filed by @likearecord

>Hello,
>
> Please create the short onion name `nex.securedrop.tor.onion` for Claudio "Nex" Guarnieri's personal instance. 
> http://7dw7foypguycptlodmkscnziw5a65ilivzz6ajiei3yhe3gsfojlqwad.onion/
>
> Thank you!

**Comment by likearecord** [comment]
checking on this :)

**Comment by zenmonkeykstop** [comment]
resolved in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/91
