### ISSUE TITLE
Onion name for CBC

### ISSUE THREAD

**Issue by likearecord** [freedomofpress/securedrop-https-everywhere-ruleset#90]
Please create the short onion name `cbcrc.securedrop.tor.onion` for CBC (http://gppg43zz5d2yfuom3yfmxnnokn3zj4mekt55onlng3zs653ty4fio6qd.onion)

Thank you!

**Comment by zenmonkeykstop** [comment]
resolved in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/91
