### ISSUE TITLE
Add Onion name for POLITICO

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#93]
Please create the short onion name politico.securedrop.tor.onion for POLITICO

Directory entry: https://securedrop.org/directory/politico/ 
Long onion address: mzi5yynpd6qqq3lnh7vnaojy36v3hcorytsut47zwkguhnorduyxwead.onion 

Thank you!

**Comment by eloquence** [comment]
As far as I can tell, this will be the first ruleset update using the new `about:rulesets` functionality in Tor Browser that replaces the HTTPSEverywhere extension. Fingers crossed it's just a drop-in from our perspective (though at least the testing procedure has changed).

**Comment by creviera** [comment]
Update: Once the ruleset is deployed (see https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/#deployment...still waiting), we can do the post-deployment check described in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/94#issue-1360271146 and close this issue.

**Comment by eloquence** [comment]
Resolved via #94.
