### ISSUE TITLE
Add Onion Name for TV2 Denmark

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#95]
Please create the short onion name `tv2.dk.securedrop.tor.onion` for TV2 Denmark

Directory entry: https://securedrop.org/directory/tv2-denmark/
Long onion address: srumyob2jq5nvppzt66aaab333n2wmq6xgkg4khfe24ixdb7umf7mtyd.onion

Thank you!

**Comment by zenmonkeykstop** [comment]
Closed by #97
