### ISSUE TITLE
Add Onion Name for Stavanger Aftenblad

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-https-everywhere-ruleset#96]
Please create the short onion name `aftenbladet.securedrop.tor.onion` for Stavanger Aftenblad

Directory entry: https://securedrop.org/directory/stavanger-aftenblad/
Long onion address: 4beybcv5e7xya4xu2nzdqkohawm32imugjtatkvmp2xwgfhcoj64slid.onion

Thank you!

**Comment by zenmonkeykstop** [comment]
Closed by #97
